server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2019011174?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    encoding: UTF-8
    cache: false

mybatis-plus:
  type-aliases-package: com.myspring.xixi.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shop:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyz
    expire: 86400
    header: Authorization

